# Generated by Django 6.0.7 on 2026-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(max_length=30, verbose_name='Телеграм')),
                ('map', models.CharField(max_length=40, verbose_name='Местоположение')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='вид тренировок')),
                ('price', models.IntegerField(verbose_name='Цена на тренировку')),
                ('bonus1', models.CharField(max_length=50, verbose_name='Что входит в цену')),
                ('bonus2', models.CharField(max_length=50, verbose_name='Что входит в цену')),
                ('bonus3', models.CharField(max_length=50, verbose_name='Что входит в цену')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='Дни')),
                ('time', models.TimeField(verbose_name='Время')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('naprav', models.CharField(max_length=20, verbose_name='Направление')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.CreateModel(
            name='Trenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothes/', verbose_name='Фото тренера')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('sport', models.CharField(max_length=20, verbose_name='Спорт')),
                ('experiense', models.IntegerField(verbose_name='Опыт')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
