# Generated by Django 6.0.7 on 2026-07-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Направление')),
            ],
        ),
        migrations.AlterField(
            model_name='trenery',
            name='image',
            field=models.ImageField(upload_to='trainers/', verbose_name='Тренеры'),
        ),
    ]
