# Generated by Django 6.0.7 on 2026-07-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_direction_alter_trenery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Регистрации'},
        ),
    ]
