# Generated by Django 6.0.7 on 2026-07-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_direction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направление'},
        ),
    ]
